In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
os.chdir('/home/externalFolder/dataFile/')

In [5]:
file_chdir=os.getcwd()

In [6]:
print(file_chdir)

/home/externalFolder/dataFile


In [7]:
filecsv_list=[]

In [8]:
for root,dirs,files in os.walk(file_chdir):
    for file in files:
        if os.path.splitext(file)[1]==".csv":
            filecsv_list.append(file)

In [9]:
print(filecsv_list[1290])

_chr1_RP1-224A6.3cut_frome_ref0711.csv


In [10]:
data=[]

In [11]:
for csv in filecsv_list:
    seqs=pd.read_csv(csv,header=None,encoding="utf8")
    seqs_list=seqs.values.flatten()
    gene_list="\t".join(seqs_list)
    data.append(gene_list)

NameError: name 'gene_list' is not defined

In [ ]:
df = open("/home/ALL.txt","a+")

In [ ]:
for line in data:
    df.write(line+"\n")

In [ ]:
df.close()

In [ ]:
#data.to_csv("ALL.csv",index=0,header=None)

In [ ]:
#print(data)

In [12]:
import pandas as pd
import numpy as np

In [13]:
#以上为数据处理过程

In [14]:
df = open("/home/externalFolder/ALL.txt","r")

In [15]:
print(df)

<_io.TextIOWrapper name='/home/externalFolder/ALL.txt' mode='r' encoding='UTF-8'>


In [16]:
allData=[]

In [17]:
for line in df.readlines():
    line=line.strip().split()
    line=list(map(float,line))
    allData.append(line)

In [18]:
allData=np.array(allData)

In [19]:
allData,type(allData),allData.shape

(array([[2.6307e-03, 6.9186e-04, 4.5192e-03, ..., 1.9398e-02, 2.3205e-01,
         1.1585e-02],
        [1.8056e-04, 6.8048e-05, 1.9893e-04, ..., 3.6776e-03, 1.5886e-01,
         5.7579e-03],
        [1.5603e-03, 1.3074e-02, 2.8531e-03, ..., 9.3641e-03, 1.4716e-01,
         1.7455e-03],
        ...,
        [2.3148e-04, 4.2565e-04, 4.7680e-04, ..., 4.6854e-04, 3.7291e-02,
         2.7685e-02],
        [1.2937e-02, 2.4322e-02, 1.6140e-02, ..., 2.1295e-02, 1.2517e-01,
         1.4104e-02],
        [6.9710e-03, 1.1012e-02, 6.4290e-03, ..., 8.7532e-03, 2.7323e-02,
         2.1891e-04]]), numpy.ndarray, (2431, 183800))

In [20]:
allData=allData.astype('float32')

In [21]:
#allData,type(allData),allData.shape

In [22]:
from keras.layers import Input, Dense
from keras.models import Model

Using TensorFlow backend.


In [23]:
import warnings
warnings.filterwarnings('ignore')

In [24]:
#压缩特征至100维

In [25]:
encoding_dim = 100

In [26]:
#生成输入层张量

In [27]:
input_img = Input(shape=(200*919,))

In [28]:
#

In [29]:
#encoded = Dense(18380,activation='relu')(input_img)

In [30]:
encoded = Dense(1800,activation='relu')(input_img)

Instructions for updating:
Colocations handled automatically by placer.


In [31]:
#

In [32]:
encoded_out_1 = Dense(encoding_dim, activation='relu')(encoded)

In [33]:
#

In [34]:
decoded = Dense(1800,activation='relu')(encoded_out_1)

In [35]:
#decoded = Dense(18380,activation='relu')(decoded)

In [36]:
#

In [37]:
decoded = Dense(200*919, activation='relu')(decoded)

In [38]:
#构建自编码器

In [39]:
autoencoder = Model(input=input_img, output=decoded)

In [40]:
#构建编码器

In [41]:
encoder = Model(input=input_img, output=encoded_out_1)

In [42]:
#encoded_input = Input(shape=(encoding_dim,))
#decoder_layer = autoencoder.layers[-1]
#decoder = Model(input=encoded_input, output=decoder_layer(encoded_input))

In [43]:
autoencoder.compile(optimizer='adam', loss='mse')

In [44]:
autoencoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 183800)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 1800)              330841800 
_________________________________________________________________
dense_2 (Dense)              (None, 100)               180100    
_________________________________________________________________
dense_3 (Dense)              (None, 1800)              181800    
_________________________________________________________________
dense_4 (Dense)              (None, 183800)            331023800 
Total params: 662,227,500
Trainable params: 662,227,500
Non-trainable params: 0
_________________________________________________________________


In [45]:
encoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 183800)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 1800)              330841800 
_________________________________________________________________
dense_2 (Dense)              (None, 100)               180100    
Total params: 331,021,900
Trainable params: 331,021,900
Non-trainable params: 0
_________________________________________________________________


In [46]:
x_train = allData[:2000,:]

In [47]:
x_test=allData[2000:,:]

In [48]:
print(x_train,type(x_train),x_train.shape)

[[2.6307e-03 6.9186e-04 4.5192e-03 ... 1.9398e-02 2.3205e-01 1.1585e-02]
 [1.8056e-04 6.8048e-05 1.9893e-04 ... 3.6776e-03 1.5886e-01 5.7579e-03]
 [1.5603e-03 1.3074e-02 2.8531e-03 ... 9.3641e-03 1.4716e-01 1.7455e-03]
 ...
 [2.9634e-04 1.7942e-03 7.0343e-04 ... 1.2877e-03 6.0729e-02 2.4778e-03]
 [7.2436e-03 8.0623e-03 1.3437e-02 ... 3.6484e-02 2.9080e-01 4.0249e-03]
 [7.3477e-04 2.0386e-03 1.1914e-03 ... 1.2099e-02 1.0486e-01 2.6258e-02]] <class 'numpy.ndarray'> (2000, 183800)


In [49]:
print(x_test,type(x_test),x_test.shape)

[[3.9200e-03 4.3770e-03 2.9266e-03 ... 7.9850e-03 6.1250e-02 3.2343e-02]
 [1.9587e-03 1.0647e-04 8.8398e-04 ... 8.2995e-04 9.3681e-02 3.2649e-03]
 [2.2034e-04 4.0516e-04 4.7584e-04 ... 2.2990e-03 9.5705e-02 1.6167e-02]
 ...
 [2.3148e-04 4.2565e-04 4.7680e-04 ... 4.6854e-04 3.7291e-02 2.7685e-02]
 [1.2937e-02 2.4322e-02 1.6140e-02 ... 2.1295e-02 1.2517e-01 1.4104e-02]
 [6.9710e-03 1.1012e-02 6.4290e-03 ... 8.7532e-03 2.7323e-02 2.1891e-04]] <class 'numpy.ndarray'> (431, 183800)


In [50]:
autoencoder.fit(x_train, x_train,
                nb_epoch=2,
                batch_size=500,
                shuffle=True,
                validation_data=(x_test, x_test))

Instructions for updating:
Use tf.cast instead.
Train on 2000 samples, validate on 431 samples
Epoch 1/2
2000/2000 [==============================] - 220s 110ms/step - loss: 0.0038 - val_loss: 0.0037
Epoch 2/2
2000/2000 [==============================] - 112s 56ms/step - loss: 0.0034 - val_loss: 0.0032


In [51]:
layer_name = 'dense_2'
intermediate_layer_model = Model(input=encoder.input,
                                 output=encoder.get_layer(layer_name).output)
intermediate_output = intermediate_layer_model.predict(x_train)

In [52]:
intermediate_output

array([[0.        , 1.1395645 , 0.        , ..., 0.53948873, 0.        ,
        0.2592251 ],
       [0.        , 0.48027712, 0.        , ..., 0.20577945, 0.        ,
        0.08158951],
       [0.        , 2.5944133 , 0.        , ..., 1.1288137 , 0.        ,
        0.45419726],
       ...,
       [0.        , 1.4346564 , 0.        , ..., 0.55547535, 0.        ,
        0.21361789],
       [0.        , 1.3988589 , 0.        , ..., 0.6179479 , 0.        ,
        0.13864951],
       [0.        , 0.9959304 , 0.        , ..., 0.37957597, 0.        ,
        0.32274866]], dtype=float32)

In [ ]:
#测试保存

In [54]:
np.save("/home/externalFolder/AE_JX_Result.npy",intermediate_output)

In [ ]:
#测试读取

In [55]:
inputdata = np.load("/home/externalFolder/AE_JX_Result.npy",encoding="latin1")

In [56]:
inputdata

array([[0.        , 1.1395645 , 0.        , ..., 0.53948873, 0.        ,
        0.2592251 ],
       [0.        , 0.48027712, 0.        , ..., 0.20577945, 0.        ,
        0.08158951],
       [0.        , 2.5944133 , 0.        , ..., 1.1288137 , 0.        ,
        0.45419726],
       ...,
       [0.        , 1.4346564 , 0.        , ..., 0.55547535, 0.        ,
        0.21361789],
       [0.        , 1.3988589 , 0.        , ..., 0.6179479 , 0.        ,
        0.13864951],
       [0.        , 0.9959304 , 0.        , ..., 0.37957597, 0.        ,
        0.32274866]], dtype=float32)

In [57]:
inputdata.shape

(2000, 100)

In [ ]:
#测试保存history

In [59]:
autoencoder.history.history["loss"]

[0.003837917640339583, 0.003365915035828948]

In [61]:
type(autoencoder.history.history["loss"][0])

numpy.float64

In [62]:
with open("/home/externalFolder/loss.txt","w") as loss:
        with open("/home/externalFolder/val_loss.txt","w") as val_loss:
            loss.writelines(str(autoencoder.history.history["loss"]))
            val_loss.writelines(str(autoencoder.history.history["val_loss"]))

In [83]:
type(intermediate_output)

numpy.ndarray

In [84]:
intermediate_output.shape

(2000, 1800)

In [85]:
layer_name21 = 'dense_21'
intermediate_layer_model = Model(input=encoder.input,
                                 output=encoder.get_layer(layer_name21).output)
intermediate_output = intermediate_layer_model.predict(x_train)

In [86]:
intermediate_output

array([[1.6576577, 3.6630821, 1.5046481, ..., 3.0319664, 0.       ,
        0.       ],
       [1.4844111, 0.7385908, 1.8486081, ..., 2.2129176, 0.       ,
        0.       ],
       [3.040242 , 1.6046256, 3.1894145, ..., 4.4009676, 0.       ,
        0.       ],
       ...,
       [6.224889 , 4.062181 , 6.2526784, ..., 4.687887 , 0.       ,
        0.       ],
       [4.433917 , 3.2582421, 1.3262172, ..., 4.4078197, 0.       ,
        0.       ],
       [1.3839215, 1.7526878, 1.9504652, ..., 3.3476288, 0.       ,
        0.       ]], dtype=float32)

In [87]:
type(intermediate_output)

numpy.ndarray

In [88]:
intermediate_output.shape

(2000, 100)