In [1]:
import pandas as pd

In [2]:
import numpy as np

In [3]:
import os

In [4]:
os.chdir('/home/externalFolder/dataFile/')

In [5]:
file_chdir=os.getcwd()

In [6]:
print(file_chdir)

/home/externalFolder/dataFile


In [7]:
filecsv_list=[]

In [8]:
for root,dirs,files in os.walk(file_chdir):
    for file in files:
        if os.path.splitext(file)[1]==".csv":
            filecsv_list.append(file)

In [9]:
print(filecsv_list[1290])

_chr1_RP1-224A6.3cut_frome_ref0711.csv


In [10]:
data=[]

In [11]:
for csv in filecsv_list:
    seqs=pd.read_csv(csv,header=None,encoding="utf8")
    seqs_list=seqs.values.flatten()
    gene_list="\t".join(seqs_list)
    data.append(gene_list)

KeyboardInterrupt: 

In [ ]:
#保存读取的文件列表

In [ ]:
df = open("/home/ALL.txt","a+")

In [ ]:
for line in data:
    df.write(line+"\n")

In [ ]:
df.close()

In [ ]:
#data.to_csv("ALL.csv",index=0,header=None)

In [ ]:
#print(data)

In [ ]:
#以上为数据处理过程

In [52]:
df = open("/home/externalFolder/ALL.txt","r")

In [53]:
print(df)

<_io.TextIOWrapper name='/home/externalFolder/ALL.txt' mode='r' encoding='UTF-8'>


In [54]:
allData=[]

In [55]:
import time

In [56]:
for line in df.readlines():
    line=line.strip().split()
    line=list(map(float,line))
    allData.append(line)

In [57]:
allData=np.array(allData)

In [58]:
allData,type(allData),allData.shape

(array([[2.6307e-03, 6.9186e-04, 4.5192e-03, ..., 1.9398e-02, 2.3205e-01,
         1.1585e-02],
        [1.8056e-04, 6.8048e-05, 1.9893e-04, ..., 3.6776e-03, 1.5886e-01,
         5.7579e-03],
        [1.5603e-03, 1.3074e-02, 2.8531e-03, ..., 9.3641e-03, 1.4716e-01,
         1.7455e-03],
        ...,
        [2.3148e-04, 4.2565e-04, 4.7680e-04, ..., 4.6854e-04, 3.7291e-02,
         2.7685e-02],
        [1.2937e-02, 2.4322e-02, 1.6140e-02, ..., 2.1295e-02, 1.2517e-01,
         1.4104e-02],
        [6.9710e-03, 1.1012e-02, 6.4290e-03, ..., 8.7532e-03, 2.7323e-02,
         2.1891e-04]]), numpy.ndarray, (2431, 183800))

In [59]:
allData=allData.astype('float32')

In [60]:
allData,type(allData),allData.shape

(array([[2.6307e-03, 6.9186e-04, 4.5192e-03, ..., 1.9398e-02, 2.3205e-01,
         1.1585e-02],
        [1.8056e-04, 6.8048e-05, 1.9893e-04, ..., 3.6776e-03, 1.5886e-01,
         5.7579e-03],
        [1.5603e-03, 1.3074e-02, 2.8531e-03, ..., 9.3641e-03, 1.4716e-01,
         1.7455e-03],
        ...,
        [2.3148e-04, 4.2565e-04, 4.7680e-04, ..., 4.6854e-04, 3.7291e-02,
         2.7685e-02],
        [1.2937e-02, 2.4322e-02, 1.6140e-02, ..., 2.1295e-02, 1.2517e-01,
         1.4104e-02],
        [6.9710e-03, 1.1012e-02, 6.4290e-03, ..., 8.7532e-03, 2.7323e-02,
         2.1891e-04]], dtype=float32), numpy.ndarray, (2431, 183800))

In [61]:
from keras.layers import Input, Dense
from keras.models import Model

In [106]:
import warnings
warnings.filterwarnings('ignore')

In [107]:
encoding_dim = 100

In [108]:
input_img = Input(shape=(200*919,))

In [109]:
encoded = Dense(encoding_dim, activation='relu')(input_img)

In [110]:
decoded = Dense(200*919, activation='relu')(encoded)

In [111]:
autoencoder = Model(input=input_img, output=decoded)

In [112]:
encoder = Model(input=input_img, output=encoded)

In [113]:
#encoded_input = Input(shape=(encoding_dim,))
#decoder_layer = autoencoder.layers[-1]
#decoder = Model(input=encoded_input, output=decoder_layer(encoded_input))

In [114]:
autoencoder.compile(optimizer='adam', loss='mse')

In [115]:
autoencoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         (None, 183800)            0         
_________________________________________________________________
dense_7 (Dense)              (None, 100)               18380100  
_________________________________________________________________
dense_8 (Dense)              (None, 183800)            18563800  
Total params: 36,943,900
Trainable params: 36,943,900
Non-trainable params: 0
_________________________________________________________________


In [121]:
encoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_7 (InputLayer)         (None, 183800)            0         
_________________________________________________________________
dense_7 (Dense)              (None, 100)               18380100  
Total params: 18,380,100
Trainable params: 18,380,100
Non-trainable params: 0
_________________________________________________________________


In [122]:
x_train = allData[:2000,:]

In [123]:
x_test=allData[2000:,:]

In [124]:
print(x_train,type(x_train),x_train.shape)

[[2.6307e-03 6.9186e-04 4.5192e-03 ... 1.9398e-02 2.3205e-01 1.1585e-02]
 [1.8056e-04 6.8048e-05 1.9893e-04 ... 3.6776e-03 1.5886e-01 5.7579e-03]
 [1.5603e-03 1.3074e-02 2.8531e-03 ... 9.3641e-03 1.4716e-01 1.7455e-03]
 ...
 [2.9634e-04 1.7942e-03 7.0343e-04 ... 1.2877e-03 6.0729e-02 2.4778e-03]
 [7.2436e-03 8.0623e-03 1.3437e-02 ... 3.6484e-02 2.9080e-01 4.0249e-03]
 [7.3477e-04 2.0386e-03 1.1914e-03 ... 1.2099e-02 1.0486e-01 2.6258e-02]] <class 'numpy.ndarray'> (2000, 183800)


In [125]:
print(x_test,type(x_test),x_test.shape)

[[3.9200e-03 4.3770e-03 2.9266e-03 ... 7.9850e-03 6.1250e-02 3.2343e-02]
 [1.9587e-03 1.0647e-04 8.8398e-04 ... 8.2995e-04 9.3681e-02 3.2649e-03]
 [2.2034e-04 4.0516e-04 4.7584e-04 ... 2.2990e-03 9.5705e-02 1.6167e-02]
 ...
 [2.3148e-04 4.2565e-04 4.7680e-04 ... 4.6854e-04 3.7291e-02 2.7685e-02]
 [1.2937e-02 2.4322e-02 1.6140e-02 ... 2.1295e-02 1.2517e-01 1.4104e-02]
 [6.9710e-03 1.1012e-02 6.4290e-03 ... 8.7532e-03 2.7323e-02 2.1891e-04]] <class 'numpy.ndarray'> (431, 183800)


In [126]:
autoencoder.fit(x_train, x_train,
                nb_epoch=50,
                batch_size=32,
                shuffle=True,
                validation_data=(x_test, x_test))

Train on 2000 samples, validate on 431 samples
Epoch 1/50
2000/2000 [==============================] - 18s 9ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 2/50
2000/2000 [==============================] - 17s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 3/50
2000/2000 [==============================] - 16s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 4/50
2000/2000 [==============================] - 17s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 5/50
2000/2000 [==============================] - 17s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 6/50
2000/2000 [==============================] - 17s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 7/50
2000/2000 [==============================] - 17s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 8/50
2000/2000 [==============================] - 17s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 9/50
2000/2000 [==============================] - 17s 8ms/step - loss: 0.0039 - val_loss: 0.0039
Epoch 10/50
2000/2000 [===

In [94]:
layer_name = 'dense_5'
intermediate_layer_model = Model(input=encoder.input,
                                 output=encoder.get_layer(layer_name).output)
intermediate_output = intermediate_layer_model.predict(x_train)

In [95]:
intermediate_output

array([[0.72749645, 0.09624985, 0.        , ..., 0.        , 0.46071273,
        0.        ],
       [0.2512621 , 0.        , 0.        , ..., 0.        , 0.15716156,
        0.        ],
       [1.4393748 , 0.        , 0.        , ..., 0.        , 0.9425086 ,
        0.05396658],
       ...,
       [0.6460837 , 0.05934263, 0.        , ..., 0.        , 0.45454234,
        0.        ],
       [0.70705444, 0.        , 0.        , ..., 0.        , 0.53505003,
        0.        ],
       [0.3941369 , 0.        , 0.        , ..., 0.        , 0.32068485,
        0.        ]], dtype=float32)

In [96]:
type(intermediate_output)

numpy.ndarray

In [97]:
intermediate_output.shape

(2000, 100)