In [5]:
import pandas as pd

In [6]:
import numpy as np

In [7]:
import os

In [4]:
os.chdir('/home/externalFolder/dataFile/')

In [5]:
file_chdir=os.getcwd()

In [6]:
print(file_chdir)

/home/externalFolder/dataFile


In [7]:
filecsv_list=[]

In [8]:
for root,dirs,files in os.walk(file_chdir):
    for file in files:
        if os.path.splitext(file)[1]==".csv":
            filecsv_list.append(file)

In [9]:
print(filecsv_list[1290])

_chr1_RP1-224A6.3cut_frome_ref0711.csv


In [10]:
data=[]

In [11]:
for csv in filecsv_list:
    seqs=pd.read_csv(csv,header=None,encoding="utf8")
    seqs_list=seqs.values.flatten()
    gene_list="\t".join(seqs_list)
    data.append(gene_list)

KeyboardInterrupt: 

In [ ]:
df = open("/home/ALL.txt","a+")

In [ ]:
for line in data:
    df.write(line+"\n")

In [ ]:
df.close()

In [ ]:
#data.to_csv("ALL.csv",index=0,header=None)

In [ ]:
#print(data)

In [11]:
import pandas as pd
import numpy as np

In [12]:
#以上为数据处理过程

In [13]:
df = open("/home/externalFolder/ALL.txt","r")

In [14]:
print(df)

<_io.TextIOWrapper name='/home/externalFolder/ALL.txt' mode='r' encoding='UTF-8'>


In [15]:
allData=[]

In [16]:
for line in df.readlines():
    line=line.strip().split()
    line=list(map(float,line))
    allData.append(line)

In [17]:
allData=np.array(allData)

In [18]:
allData,type(allData),allData.shape

(array([[2.6307e-03, 6.9186e-04, 4.5192e-03, ..., 1.9398e-02, 2.3205e-01,
         1.1585e-02],
        [1.8056e-04, 6.8048e-05, 1.9893e-04, ..., 3.6776e-03, 1.5886e-01,
         5.7579e-03],
        [1.5603e-03, 1.3074e-02, 2.8531e-03, ..., 9.3641e-03, 1.4716e-01,
         1.7455e-03],
        ...,
        [2.3148e-04, 4.2565e-04, 4.7680e-04, ..., 4.6854e-04, 3.7291e-02,
         2.7685e-02],
        [1.2937e-02, 2.4322e-02, 1.6140e-02, ..., 2.1295e-02, 1.2517e-01,
         1.4104e-02],
        [6.9710e-03, 1.1012e-02, 6.4290e-03, ..., 8.7532e-03, 2.7323e-02,
         2.1891e-04]]), numpy.ndarray, (2431, 183800))

In [19]:
allData=allData.astype('float32')

In [20]:
#allData,type(allData),allData.shape

In [21]:
from keras.layers import Input, Dense
from keras.models import Model

Using TensorFlow backend.


In [22]:
import warnings
warnings.filterwarnings('ignore')

In [23]:
#压缩特征至100维

In [24]:
encoding_dim = 100

In [25]:
#生成输入层张量

In [26]:
input_img = Input(shape=(200*919,))

In [27]:
#

In [28]:

encoded_output_1 = Dense(18000,activation='relu')(input_img)
decoded=Dense(200*919,activation='relu')(encoded_output_1)

Instructions for updating:
Colocations handled automatically by placer.


In [29]:
input_imge_2=Input(shape=(18000,))

encoded_output_2=Dense(1800,activation='relu')(input_image_2)
encoded = Dense(18000,activation='relu')(encoded)

In [30]:
#

In [31]:
input_image_3=Input(shape=(1800,))
encoded_out_1 = Dense(encoding_dim, activation='relu')(input_image_3)
decoded=Dense(1800)

In [32]:
#

In [33]:
decoded = Dense(1838,activation='relu')(encoded_out_1)

In [34]:
decoded = Dense(18380,activation='relu')(decoded)

In [35]:
#

In [36]:
decoded = Dense(200*919, activation='relu')(decoded)

In [37]:
#构建自编码器

In [38]:
autoencoder = Model(input=input_img, output=decoded)

In [ ]:
#构建编码器

In [50]:
encoder = Model(input=input_img, output=encoded_out_1)

In [ ]:
#encoded_input = Input(shape=(encoding_dim,))
#decoder_layer = autoencoder.layers[-1]
#decoder = Model(input=encoded_input, output=decoder_layer(encoded_input))

In [51]:
autoencoder.compile(optimizer='adam', loss='mse')

In [52]:
autoencoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 183800)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 18380)             3378262380
_________________________________________________________________
dense_2 (Dense)              (None, 1838)              33784278  
_________________________________________________________________
dense_3 (Dense)              (None, 100)               183900    
_________________________________________________________________
dense_4 (Dense)              (None, 1838)              185638    
_________________________________________________________________
dense_5 (Dense)              (None, 18380)             33800820  
_________________________________________________________________
dense_6 (Dense)              (None, 183800)            3378427800
Total para

In [53]:
encoder.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         (None, 183800)            0         
_________________________________________________________________
dense_1 (Dense)              (None, 18380)             3378262380
_________________________________________________________________
dense_2 (Dense)              (None, 1838)              33784278  
_________________________________________________________________
dense_3 (Dense)              (None, 100)               183900    
Total params: 3,412,230,558
Trainable params: 3,412,230,558
Non-trainable params: 0
_________________________________________________________________


In [54]:
x_train = allData[:2000,:]

In [55]:
x_test=allData[2000:,:]

In [56]:
print(x_train,type(x_train),x_train.shape)

[[2.6307e-03 6.9186e-04 4.5192e-03 ... 1.9398e-02 2.3205e-01 1.1585e-02]
 [1.8056e-04 6.8048e-05 1.9893e-04 ... 3.6776e-03 1.5886e-01 5.7579e-03]
 [1.5603e-03 1.3074e-02 2.8531e-03 ... 9.3641e-03 1.4716e-01 1.7455e-03]
 ...
 [2.9634e-04 1.7942e-03 7.0343e-04 ... 1.2877e-03 6.0729e-02 2.4778e-03]
 [7.2436e-03 8.0623e-03 1.3437e-02 ... 3.6484e-02 2.9080e-01 4.0249e-03]
 [7.3477e-04 2.0386e-03 1.1914e-03 ... 1.2099e-02 1.0486e-01 2.6258e-02]] <class 'numpy.ndarray'> (2000, 183800)


In [57]:
print(x_test,type(x_test),x_test.shape)

[[3.9200e-03 4.3770e-03 2.9266e-03 ... 7.9850e-03 6.1250e-02 3.2343e-02]
 [1.9587e-03 1.0647e-04 8.8398e-04 ... 8.2995e-04 9.3681e-02 3.2649e-03]
 [2.2034e-04 4.0516e-04 4.7584e-04 ... 2.2990e-03 9.5705e-02 1.6167e-02]
 ...
 [2.3148e-04 4.2565e-04 4.7680e-04 ... 4.6854e-04 3.7291e-02 2.7685e-02]
 [1.2937e-02 2.4322e-02 1.6140e-02 ... 2.1295e-02 1.2517e-01 1.4104e-02]
 [6.9710e-03 1.1012e-02 6.4290e-03 ... 8.7532e-03 2.7323e-02 2.1891e-04]] <class 'numpy.ndarray'> (431, 183800)


In [ ]:
autoencoder.fit(x_train, x_train,
                nb_epoch=50,
                batch_size=500,
                shuffle=True,
                validation_data=(x_test, x_test))

Train on 2000 samples, validate on 431 samples
Epoch 1/50


In [ ]:
layer_name = 'dense_9'
intermediate_layer_model = Model(input=encoder.input,
                                 output=encoder.get_layer(layer_name).output)
intermediate_output = intermediate_layer_model.predict(x_train)

In [ ]:
intermediate_output

In [ ]:
type(intermediate_output)

In [ ]:
intermediate_output.shape